server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://147.45.148.118:5432/prmo_v2
    username: postgres
    password: "RiUmS\|C53g}z\"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        cache:
  liquibase:
    change-log: classpath:liquibase/changelog.yaml

#  web:
#    resources:
#      cache:
#        cachecontrol:
#          max-age: 365d
#  thymeleaf:
#    prefix: classpath:/templates/
#    cache: false
